language: node_js

node_js:
  - "0.10"
  - "0.11"

matrix:
  allow_failures:
    - node_js: "0.11"
  
script: "npm run-script test-travis"


after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --ui=bdd --reporter=xunit-file
  - ./node_modules/.bin/istanbul report cobertura --dir shippable/codecoverage/
  
notifications:
     email:
         recipients:
             - vidya@shippable.com
             - buildsampletest@gmail.com
         on_success: always
         on_failure: always

archive: true
